[project]
# T3 Chat Cloneathon - Competition Configuration
name = "T3 Chat Clone - Competition Edition"
description = "Advanced AI chat application with multi-model support, file uploads, and chat history"
author = "T3 Cloneathon Team"

[ui]
# Enhanced UI settings for professional appearance
name = "🚀 T3 Chat Clone"
description = "Experience the future of AI conversation"
github = "https://github.com/your-repo/t3-chat-clone"
theme = "light"
default_collapse_content = false
default_expand_messages = true
hide_cot = false

[features]
# Enable all bonus features
spontaneous_file_upload = {
    enabled = true,
    accept = ["image/png", "image/jpeg", "image/gif", "application/pdf", "text/plain", "text/markdown", "application/json"],
    max_size_mb = 10,
    max_files = 5
}

[meta]
generated_by = "0.0.0" 