services:
  - type: web
    name: t3-chat-django
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings_production"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" 