services:
  - type: web
    name: t3-chat-django
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements_render.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py setup_t3_chat
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11.0 